custom_modules/hr_recruitment_psi/__init__.py
custom_modules/hr_recruitment_psi/models/hr_recruitment.py
custom_modules/hr_recruitment_psi/report/__init__.py
custom_modules/hr_recruitment_psi/report/hr_recruitment_report.py

Issue poste reporting

---

custom_modules/hr_recruitment_psi/models/hr_recruitment.py
custom_modules/website_psi_job_recruitment/controllers/main.py
custom_modules/website_psi_job_recruitment/views/hr_recruitment_views.xml

Formulaire candidature sur le siteweb

Issues formulaire candidature

---

custom_modules/hr_recruitment_psi/models/hr_recruitment.py

FIX: Age champ calculé depuis la date de naissance

---

custom_modules/hr_recruitment_psi/models/hr_recruitment.py
custom_modules/website_psi_job_recruitment/views/hr_recruitment_views.xml

web_retour_formulaire > develop

FIX : formulaire candidature

---

custom_modules/hr_recruitment_psi/models/hr_job.py
custom_modules/hr_recruitment_psi/views/hr_job_views.xml

FIX: lieu de travail en many2many

---

custom_modules/hr_recruitment_psi/models/hr_recruitment.py

ADD: Calcul moyenne note test

---

custom_modules/hr_contract_psi/__manifest__.py
custom_modules/hr_contract_psi/data/hr_contract_data.xml
custom_modules/hr_contract_psi/data/mail_template_hr_contract_data.xml
custom_modules/hr_contract_psi/models/hr_contract.py
custom_modules/hr_contract_psi/views/hr_contract_views.xml

Mise en place de déclenchement de notification.

ADD : Mail automatique

---

custom_modules/hr_contract_psi/__manifest__.py
custom_modules/hr_contract_psi/data/hr_contract_data.xml
custom_modules/hr_contract_psi/data/mail_template_hr_contract_data.xml
custom_modules/hr_contract_psi/models/hr_contract.py
custom_modules/hr_contract_psi/views/hr_contract_views.xml
custom_modules/hr_recruitment_psi/models/hr_job.py
custom_modules/hr_recruitment_psi/models/hr_recruitment.py
custom_modules/hr_recruitment_psi/views/hr_job_views.xml
custom_modules/hr_recruitment_psi/views/hr_recruitement_views.xml
custom_modules/website_psi_job_recruitment/controllers/main.py
custom_modules/website_psi_job_recruitment/views/hr_recruitment_views.xml

correction-poste-candidature > develop

Correction poste candidature

---

custom_modules/hr_contract_psi/data/hr_contract_data.xml
custom_modules/hr_contract_psi/data/mail_template_hr_contract_data.xml
custom_modules/hr_contract_psi/models/hr_contract.py

contrats-tache-automatique > develop

FIX : Tache automatique

---

custom_modules/hr_contract_psi/data/hr_contract_data.xml
custom_modules/hr_contract_psi/data/mail_template_hr_contract_data.xml
custom_modules/hr_contract_psi/models/hr_contract.py
custom_modules/hr_contract_psi/views/hr_contract_views.xml

Contrats rg50 rappel suivi fin essai

---

custom_modules/hr_contract_psi/data/hr_contract_data.xml
custom_modules/hr_contract_psi/data/mail_template_hr_contract_data.xml
custom_modules/hr_contract_psi/models/hr_contract.py

contrats-rg47-48-49-64-50 > new-contrats

FIX : mail template and function

---

custom_modules/hr_employee_psi/__manifest__.py
custom_modules/hr_employee_psi/data/hr_employee_data.xml
custom_modules/hr_employee_psi/data/mail_template_hr_employee_data.xml
custom_modules/hr_employee_psi/models/hr_employee.py

contrat-rg14-suivi-date-d'anniversaire > new-contrats

ADD : Suivie de date d'anniversaire

---

custom_modules/hr_contract_psi/models/hr_contract.py
custom_modules/hr_contract_psi/views/hr_contract_views.xml

ADD : rg63 separation evenement

---

custom_modules/hr_contract_psi/__manifest__.py
custom_modules/hr_contract_psi/data/hr_contract_data.xml
custom_modules/hr_contract_psi/data/mail_template_hr_contract_data.xml
custom_modules/hr_contract_psi/models/hr_contract.py
custom_modules/hr_contract_psi/views/hr_contract_views.xml
custom_modules/hr_employee_psi/__manifest__.py
custom_modules/hr_employee_psi/data/hr_employee_cron.xml
custom_modules/hr_employee_psi/data/hr_employee_data.xml
custom_modules/hr_employee_psi/data/mail_template_hr_employee_data.xml
custom_modules/hr_employee_psi/models/hr_employee.py
custom_modules/hr_employee_psi/views/hr_employee_views.xml
custom_modules/hr_recruitment_psi/models/hr_job.py
custom_modules/hr_recruitment_psi/models/hr_recruitment.py
custom_modules/hr_recruitment_psi/views/hr_recruitement_views.xml
custom_modules/hr_recruitment_psi/views/hr_recruitement_views_stagiaire.xml
custom_modules/hr_recruitment_psi/views/hr_recruitement_wkf.xml

New contrats

---

custom_modules/hr_employee_psi/data/hr_employee_data.xml
custom_modules/hr_employee_psi/data/mail_template_hr_employee_data.xml
custom_modules/hr_employee_psi/models/hr_employee.py

contrat-rg14-suivi-date-d'anniversaire > new-contrats

FIX : rappel date d'anniversaire

---

custom_modules/hr_contract_psi/data/hr_contract_data.xml
custom_modules/hr_contract_psi/models/hr_contract.py
custom_modules/hr_contract_psi/views/hr_contract_views.xml

ADD : Suivi contrat cloture profil

---

custom_modules/hr_contract_psi/data/mail_template_hr_contract_data.xml
custom_modules/hr_contract_psi/models/hr_contract.py
custom_modules/hr_contract_psi/views/hr_contract_views.xml
custom_modules/hr_employee_psi/data/mail_template_hr_employee_data.xml

contrats rg53 suivi essai ko > new-contrats

ADD : Suivi fin essai KO

---

custom_modules/hr_employee_psi/models/hr_employee.py
custom_modules/hr_employee_psi/views/hr_employee_views.xml

contrats-nombre-profil-non-complet > new-contrats

ADD : Nombre profil non complet

---

custom_modules/hr_contract_psi/data/hr_contract_data.xml

r16-contrat-bridger-insightedate > new-contrats

FIX : bridger_insight

---

custom_modules/hr_employee_psi/models/hr_employee.py
custom_modules/hr_employee_psi/views/hr_employee_views.xml

ADD : rg56 declaration interet

---

custom_modules/hr_contract_psi/models/hr_contract.py
custom_modules/hr_contract_psi/views/hr_contract_views.xml

contrats-rupture-renvoyer-mail > new-contrats

ADD : Bouton renvoyer email - rupture contrat

---

custom_modules/hr_employee_psi/data/hr_employee_cron.xml
custom_modules/hr_employee_psi/data/mail_template_hr_employee_data.xml
custom_modules/hr_employee_psi/models/hr_employee.py
custom_modules/hr_employee_psi/views/hr_employee_views.xml

contrat declaration ethique > new-contrats

Contrats declaration ethique

---

custom_modules/hr_employee_psi/models/hr_employee.py
custom_modules/hr_employee_psi/views/hr_employee_views.xml

contrats-declaration-interet > new-contrats

FIX : Declaration interet - cours d'ethique

---

custom_modules/hr_contract_psi/__init__.py
custom_modules/hr_contract_psi/controllers/__init__.py
custom_modules/hr_contract_psi/controllers/main.py
custom_modules/hr_contract_psi/data/mail_template_evenement_professionnel.xml
custom_modules/hr_contract_psi/data/mail_template_hr_contract_data.xml
custom_modules/hr_contract_psi/models/hr_contract.py
custom_modules/hr_contract_psi/views/hr_contract_views.xml

Contract rg32 checkout > new-contrats

Contract rg32 checkout

---

custom_modules/hr_contract_psi/models/hr_contract.py
custom_modules/hr_contract_psi/views/hr_contract_views.xml

Contract rg27 separation preavis > new-contract

ADD : Separation préavis

---

custom_modules/hr_contract_psi/data/mail_template_hr_contract_data.xml
custom_modules/hr_contract_psi/models/hr_contract.py

Contract rg32 checkout fix bugs > new-contrats

Contract rg32 checkout fix bugs

---

custom_modules/hr_employee_psi/models/hr_employee.py
custom_modules/hr_holidays_psi/__manifest__.py
custom_modules/hr_holidays_psi/models/hr_holidays_psi.py
custom_modules/hr_holidays_psi/views/hr_holidays_views.xml

Absences rg34 demande d absence j3 > Absences

ADD : Congé par catégorie + La demande d’absence J-3

---

custom_modules/hr_holidays_psi/__manifest__.py
custom_modules/hr_holidays_psi/data/hr_holidays_cron.xml
custom_modules/hr_holidays_psi/data/hr_holidays_data.xml
custom_modules/hr_holidays_psi/data/mail_template_hr_holidays_data.xml
custom_modules/hr_holidays_psi/models/hr_holidays_psi.py
custom_modules/hr_holidays_psi/views/hr_holidays_views.xml

absences-conges-maladie > absences

Absences conges maladie

---

custom_modules/hr_holidays_psi/models/hr_holidays_psi.py

FIX : psi_category_id

---

custom_modules/hr_holidays_psi/data/hr_holidays_data.xml
custom_modules/hr_holidays_psi/models/hr_holidays_psi.py

ADD : conge sans soldes

---

custom_modules/hr_holidays_psi/data/hr_holidays_data.xml
custom_modules/hr_holidays_psi/models/hr_holidays_psi.py
custom_modules/hr_holidays_psi/views/hr_holidays_views.xml

absences demande permission > absences

ADD : Demande permission

---

custom_modules/hr_holidays_psi/models/hr_holidays_psi.py

rg37 demande absences conge sans soldes > Absences

FIX : code

---

custom_modules/hr_holidays_psi/models/hr_holidays_psi.py
custom_modules/hr_holidays_psi/views/hr_holidays_views.xml

demande absence conge nombre de doit > absences

ADD : demande absence conge nombre de doit

---

custom_modules/hr_holidays_psi/models/hr_holidays_psi.py

ADD : congé cloture

---

custom_modules/hr_holidays_psi/models/hr_holidays_psi.py
custom_modules/hr_holidays_psi/views/hr_holidays_views.xml

Absences rg39 circuit de validation > Absences

ADD : circuit de validation

---

custom_modules/hr_holidays_psi/data/hr_holidays_data.xml
custom_modules/hr_holidays_psi/models/hr_holidays_psi.py
custom_modules/hr_holidays_psi/views/hr_holidays_configuration_views.xml
custom_modules/hr_holidays_psi/views/hr_holidays_views.xml

Absences permission type > absences

ADD : Absences permission type

---

custom_modules/hr_holidays_psi/__init__.py
custom_modules/hr_holidays_psi/__manifest__.py
custom_modules/hr_holidays_psi/models/hr_holidays_psi.py
custom_modules/hr_holidays_psi/report/__init__.py
custom_modules/hr_holidays_psi/report/report_request_for_absences.py
custom_modules/hr_holidays_psi/report/report_request_for_absences.xml
custom_modules/hr_holidays_psi/report/report_request_for_absences_template.xml
custom_modules/hr_holidays_psi/views/hr_holidays_views.xml

rg38 demande absence unique > Absence

Absences rg38 demande absence unique

---

custom_modules/hr_holidays_psi/__manifest__.py
custom_modules/hr_holidays_psi/data/hr_holidays_cron.xml
custom_modules/hr_holidays_psi/data/mail_template_hr_holidays_data.xml
custom_modules/hr_holidays_psi/models/hr_holidays_psi.py

absences rappel aux assistantes > absences

ADD : rappel aux assistantes et coordinateurs

---

custom_modules/hr_recruitment_psi/models/hr_recruitment.py
custom_modules/hr_recruitment_psi/views/hr_job_views.xml
custom_modules/website_psi_job_recruitment/controllers/main.py

FIX : bugs formulaire candidature > develop

FIX : bugs formulaire candidature

---

custom_modules/hr_contract_psi/data/mail_template_hr_contract_data.xml
custom_modules/hr_contract_psi/models/hr_contract.py

Contracts fix suivie fin contrat demande embauche  > New contrats

FIX : demande d'embauche

---

custom_modules/hr_contract_psi/data/mail_template_hr_contract_data.xml
custom_modules/hr_contract_psi/models/hr_contract.py
custom_modules/hr_recruitment_psi/views/hr_job_views.xml

Contrat suivi fin contrat d'embauche > new-contrat

FIX : suivie fin de contrat

---

custom_modules/hr_contract_psi/data/hr_contract_data.xml
custom_modules/hr_contract_psi/data/mail_template_hr_contract_data.xml
custom_modules/hr_contract_psi/models/hr_contract.py
custom_modules/hr_employee_psi/data/hr_employee_cron.xml
custom_modules/hr_employee_psi/data/mail_template_hr_employee_data.xml
custom_modules/hr_employee_psi/models/hr_employee.py

contrat fix cron mail fin essai > new-contrats

FIX : Cron - mail - Contrat&Employé

---

custom_modules/hr_holidays_psi/data/hr_holidays_data.xml
custom_modules/hr_holidays_psi/models/hr_holidays_psi.py

absence change attribution conge > absences

FIX : attribution conge

---

custom_modules/hr_holidays_psi/data/hr_holidays_cron.xml
custom_modules/hr_holidays_psi/models/hr_holidays_psi.py
custom_modules/hr_holidays_psi/report/report_request_for_absences_template.xml
custom_modules/hr_recruitment_psi/models/hr_recruitment.py

FIX : demande d'absence impression + ajouter droit de conges automatique

---

custom_modules/hr_contract_psi/data/hr_contract_data.xml
custom_modules/hr_contract_psi/data/mail_template_hr_contract_data.xml
custom_modules/hr_contract_psi/models/hr_contract.py
custom_modules/hr_employee_psi/data/hr_employee_cron.xml
custom_modules/hr_employee_psi/data/mail_template_hr_employee_data.xml
custom_modules/hr_employee_psi/models/hr_employee.py
custom_modules/hr_holidays_psi/data/hr_holidays_data.xml
custom_modules/hr_holidays_psi/models/hr_holidays_psi.py

FIX : Cron mail

---

custom_modules/hr_holidays_psi/models/hr_holidays_psi.py
custom_modules/hr_holidays_psi/views/hr_holidays_views.xml

absences reporting liste permanent > absences

Absences reporting liste permanent moi courant

---

custom_modules/hr_timesheet_psi/__manifest__.py
custom_modules/hr_timesheet_psi/data/hr_timesheet_data.xml
custom_modules/hr_timesheet_psi/models/__init__.py
custom_modules/hr_timesheet_psi/models/hr_timesheet.py
custom_modules/hr_timesheet_psi/models/hr_timesheet_psi.py
custom_modules/hr_timesheet_psi/models/res_company.py
custom_modules/hr_timesheet_psi/views/hr_timesheet_psi_views.xml
custom_modules/hr_timesheet_psi/views/hr_timesheet_views.xml

timesheet heure supp > timesheets

ADD : timesheet demande heure supp

---

custom_modules/hr_timesheet_psi/models/hr_timesheet_psi.py

timesheet heure supp > timesheets

FIX : Timesheet heure supplementaire

---

custom_modules/hr_timesheet_psi/data/hr_timesheet_cron.xml
custom_modules/hr_timesheet_psi/data/hr_timesheet_data.xml
custom_modules/hr_timesheet_psi/data/resource_calendar_data.xml
custom_modules/hr_timesheet_psi/models/hr_timesheet.py
custom_modules/hr_timesheet_psi/models/hr_timesheet_psi.py
custom_modules/hr_timesheet_psi/views/hr_timesheet_psi_views.xml

timesheets-dev-live > timesheets

Timesheets dev live

---

custom_modules/hr_timesheet_psi/views/hr_timesheet_psi_views.xml

timesheets-dev-live > timesheets

FIX: change date to time

---

custom_modules/hr_timesheet_psi/views/hr_timesheet_psi_views.xml
custom_modules/hr_timesheet_psi/views/resource_views_psi.xml

FIX : invisible task

---

custom_modules/project_psi/__init__.py
custom_modules/project_psi/__manifest__.py
custom_modules/project_psi/models/__init__.py
custom_modules/project_psi/models/project_psi.py
custom_modules/project_psi/views/project_views.xml

Project fix

---

custom_modules/hr_timesheet_psi/models/__init__.py
custom_modules/hr_timesheet_psi/models/account_analytic_line.py
custom_modules/hr_timesheet_psi/views/hr_timesheet_psi_views.xml

FIX : force create to write at view grid

---

custom_modules/hr_holidays_psi/models/hr_holidays_psi.py
custom_modules/hr_holidays_psi/views/hr_holidays_views.xml
custom_modules/hr_timesheet_psi/models/hr_timesheet.py
custom_modules/hr_timesheet_psi/models/hr_timesheet_psi.py
custom_modules/project_psi/models/project_psi.py

Fix : 2 dates, contrôles timesheet

Fix : 2 dates, contrôls timesheet

---

custom_modules/hr_employee_psi/models/hr_employee.py
custom_modules/hr_employee_psi/views/hr_employee_views.xml

FIX : Nom employee

---

custom_modules/hr_employee_psi/models/hr_employee.py
custom_modules/hr_employee_psi/views/hr_employee_views.xml

FIX : onchange nom prenoms

---

custom_modules/hr_holidays_psi/views/hr_holidays_views.xml

Holidays public

---

custom_modules/hr_holidays_psi/views/hr_holidays_views.xml

FIX : Edit public holidays
